// <auto-generated />
using System;
using HallOfTodos.API.Contexts;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace HallOfTodos.API.Migrations
{
    [DbContext(typeof(TodoContext))]
    [Migration("20200403134247_AddedForiegnKeyAttributeToTodNoteEntity")]
    partial class AddedForiegnKeyAttributeToTodNoteEntity
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "3.1.3")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("HallOfTodos.API.Entities.TodoEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<bool>("Complete")
                        .HasColumnType("bit");

                    b.Property<DateTime?>("CompleteDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Doing")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("DueDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("Todo")
                        .IsRequired()
                        .HasColumnType("nvarchar(50)")
                        .HasMaxLength(50);

                    b.HasKey("Id");

                    b.ToTable("Todos");

                    b.HasData(
                        new
                        {
                            Id = new Guid("72038873-4a70-455a-afaa-6ad787633ee3"),
                            Complete = false,
                            Description = "Test 123",
                            Doing = "Dave",
                            Todo = "Buy Organic Eggs from Whole Foods"
                        },
                        new
                        {
                            Id = new Guid("7be07a44-1b2b-4d5a-ad96-2ecc3699ae90"),
                            Complete = false,
                            Description = "Picanha boudin meatloaf turducken ribeye ham hock, chuck flank doner tri-tip swine. T-bone brisket prosciutto buffalo tenderloin. Kielbasa kevin cow, shank meatball beef doner. Turkey picanha beef ribs, bresaola prosciutto shoulder buffalo cupim alcatra drumstick shank pork belly ham capicola. Jerky brisket shankle tail landjaeger. Boudin spare ribs salami t-bone, bresaola pastrami filet mignon pig ham. Pork belly flank shankle tongue cow strip steak picanha short ribs shoulder turkey rump burgdoggen pork frankfurter.",
                            Doing = "Dave",
                            Todo = "Buy cat food"
                        },
                        new
                        {
                            Id = new Guid("c76cdf90-2beb-41d8-99c6-c4d0f0e783d9"),
                            Complete = false,
                            Description = "Test 123",
                            Doing = "Dave",
                            Todo = "take suit to cleaners"
                        },
                        new
                        {
                            Id = new Guid("27c7c8b9-5d8f-4334-b43c-38e6a694840c"),
                            Complete = false,
                            Description = "Test 123",
                            Doing = "Dave",
                            Todo = "yeah"
                        });
                });

            modelBuilder.Entity("HallOfTodos.API.Entities.TodoNote", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Details")
                        .HasColumnType("nvarchar(200)")
                        .HasMaxLength(200);

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("nvarchar(50)")
                        .HasMaxLength(50);

                    b.Property<Guid>("TodoId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("WrittenBy")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("TodoId");

                    b.ToTable("TodoNotes");

                    b.HasData(
                        new
                        {
                            Id = new Guid("cb74c57a-88ad-4b90-9075-a7dde972c047"),
                            Details = "see above",
                            Title = "no eggs at Whole foods",
                            TodoId = new Guid("72038873-4a70-455a-afaa-6ad787633ee3")
                        },
                        new
                        {
                            Id = new Guid("a59545f8-1698-4b5d-a4e9-ca562876b351"),
                            Details = "plenty of eggs here",
                            Title = "went to kroger",
                            TodoId = new Guid("72038873-4a70-455a-afaa-6ad787633ee3")
                        },
                        new
                        {
                            Id = new Guid("06d9ba77-0ba3-4395-b618-61cde7e1d94c"),
                            Details = "see above",
                            Title = "got cat food at pet smart",
                            TodoId = new Guid("7be07a44-1b2b-4d5a-ad96-2ecc3699ae90")
                        },
                        new
                        {
                            Id = new Guid("85c72ac1-516c-40cd-858d-11e6c6982ae3"),
                            Details = "plenty of cat food here",
                            Title = "30 dollars a bag",
                            TodoId = new Guid("7be07a44-1b2b-4d5a-ad96-2ecc3699ae90")
                        },
                        new
                        {
                            Id = new Guid("977cad2e-94b7-49c7-85b3-6aab233d7e03"),
                            Details = "see above",
                            Title = "used heritage cleaners",
                            TodoId = new Guid("c76cdf90-2beb-41d8-99c6-c4d0f0e783d9")
                        },
                        new
                        {
                            Id = new Guid("082e2722-f38d-4563-8289-94c567685d9a"),
                            Details = "plenty of chips here - test",
                            Title = "3 dollars a bag - test",
                            TodoId = new Guid("27c7c8b9-5d8f-4334-b43c-38e6a694840c")
                        });
                });

            modelBuilder.Entity("HallOfTodos.API.Entities.TodoNote", b =>
                {
                    b.HasOne("HallOfTodos.API.Entities.TodoEntity", "Todo")
                        .WithMany("Notes")
                        .HasForeignKey("TodoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });
#pragma warning restore 612, 618
        }
    }
}
